"""TEE 全量对齐：补齐 34 张缺失表（spec 2026-07-27-tee-full-table-alignment）

Revision ID: 0004_full_table_alignment
Revises: 0003_merge_tee_heads
Create Date: 2026-07-27

DDL 由 scripts/tee/derive_tee_ddl.py 从 prod RDS 实库派生后人工审校，不是手抄
（手抄失真有前科，见 reconciler.TABLES 的注释）。

⚠️ 本 revision 会重新创建 0002_drop_retired_supervisor 刚删掉的两张表
（agent_runtime_instances / agent_runtime_supervisor_heartbeats）。这**不是**误操作，
是 2026-07-27 用户在"TEE 全量对齐"目标下的明确决定：0002 当时按"V1 supervisor 已退役"
撤销了这两张镜像，但实测 V1 在 RDS 侧仍然活着——prod 有 220 行 agent_runtime_instances
和 1 行心跳，backend 也仍在写（db.py:335 / agent_runtime/leases.py:51）。既然目标是让
TEE 成为 RDS 的完整副本以备扶正，就不能留这个缺口。
已知代价（用户接受）：V1 真正退役后这两张表会在 RDS 侧消失，届时 TEE 侧需要再删一次。
两表的列定义 + 索引原样复用 0001 baseline / 0002_drop_retired_supervisor 的 downgrade
定义（经与 prod 当前实际 schema 核对逐列一致）。

四类改动相对 RDS 原始 DDL：
1. CIPHERTEXT lane（7 张：chat_message_archive / model_api_credentials /
   v2_conversation_summary / v2_conversation_summary_segments / v2_trajectory_events /
   v2_trajectory_reviews / v2_workspace_entries）的信封列在 TEE 侧存明文，故不带 RDS
   那边的信封 CHECK 约束（ck_v2_trajectory_envelope / ck_v2_trajectory_review_envelope
   要求 body_ct/K_enclave 等键存在，明文行必然违反）。derive_tee_ddl.py 本身不导出任何
   CHECK 约束，所以这两条不是"从草稿里删掉"，而是从一开始就没被派生出来——本轮审校
   逐表核对 pg_constraint 确认这是仅有的两条信封 CHECK，且没有别的 CHECK 意外带入。
2. per-user FK 指向 TEE 自己的 users 表，ON DELETE CASCADE（与 RDS 侧逐表核对一致，
   包括 v2_turn_metrics.user_id 可空但仍带 FK 的这一特例）。RDS 侧还有一批表间 FK
   （如 agent_action_queue.job_id → agent_jobs.id、v2_trajectory_streams.job_id →
   agent_jobs.id 等），本 revision 未带：TEE 侧各表走独立的 lane 刷新（SNAPSHOT 是
   逐表 TRUNCATE+COPY），带上跨表 FK 会在刷新顺序不确定时产生级联误删，留给
   Task 5/7 的写路径落地后按需再评估是否需要。
3. 索引只带 PK；两张恢复表额外带回原有的 lease/updated_at 索引（有明确读路径在用），
   其余 32 张新表不带任何非 PK 索引——TEE 是副本，写模式是批量替换，Task 5/7 前没有
   已知读路径，多余索引只是写放大。RDS 侧还有几个业务 UNIQUE 约束（如
   v2_trajectory_events 的 (job_id, idempotency_key)）出于同样理由未带。
4. 7 张 RDS 侧用 `DEFAULT nextval('<table>_id_seq'::regclass)` 实现自增（非真 IDENTITY，
   is_identity=NO）的 id 列，在 TEE 侧改写成 `GENERATED BY DEFAULT AS IDENTITY`：直接
   照抄 `nextval('...'::regclass)` 在空库上建表会报错（regclass 转型在 DDL 解析期就要
   求该序列已存在，本地全新库验证时实测复现），需要先手工 CREATE SEQUENCE 才能用原写法，
   而 IDENTITY 列自带隐式序列、语义等价（仍接受显式插入值，不强制 OVERRIDING SYSTEM
   VALUE，因为是 BY DEFAULT 不是 ALWAYS）且不需要额外语句。真正的 IDENTITY 列
   （v2_conversation_summary_segments.segment_id 是 GENERATED ALWAYS，v2_effect_outbox.
   enqueue_seq 是 GENERATED BY DEFAULT）与 RDS 原样一致，未改动。

派生脚本本身还有两处 information_schema 的已知盲区，本轮人工核对 pg_catalog.
format_type() 后修正（脚本文件未改，因为这是"审校"步骤要做的事，不是脚本 bug 到了
非改不可的地步——盲区已用具体列名记录在这里，供下次派生时提前留意）：
- ARRAY 列：information_schema.columns.data_type 对数组列一律显示 'ARRAY'，丢了元素
  类型。v2_conversation_summary.materialized_segment_ids 与
  v2_conversation_summary_segments.child_segment_ids 实际都是 bigint[]。
- 定长 character 列：v2_mcp_mutation_attempts.call_key / tool_fingerprint 的
  information_schema.data_type 是裸 'character'（不含长度），照抄会建成
  character(1) 截断真实值；核对 pg_catalog.format_type 后订正为 character(64)。

DDL 幂等（IF NOT EXISTS），与 0001 baseline 的安全性质一致。
"""

from alembic import op

revision = "0004_full_table_alignment"
down_revision = "0003_merge_tee_heads"
branch_labels = None
depends_on = None


_DDL = """
-- ---------------------------------------------------------------------
-- MIRROR —— 重建 0002_drop_retired_supervisor 撤销的两张表（见上方 docstring）
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS agent_runtime_instances (
    user_id           TEXT PRIMARY KEY,
    driver            TEXT NOT NULL,
    status            TEXT NOT NULL,
    pid               INTEGER,
    lease_owner       TEXT,
    lease_expires_at  TIMESTAMPTZ,
    session_ref       TEXT,
    runtime_home      TEXT NOT NULL,
    last_heartbeat_at TIMESTAMPTZ,
    last_active_at    TIMESTAMPTZ,
    error             TEXT,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS agent_runtime_instances_lease_idx
    ON agent_runtime_instances (lease_owner, lease_expires_at);

CREATE TABLE IF NOT EXISTS agent_runtime_supervisor_heartbeats (
    owner           TEXT PRIMARY KEY,
    host            TEXT,
    shard_index     INTEGER NOT NULL DEFAULT 0,
    shard_count     INTEGER NOT NULL DEFAULT 1,
    max_children    INTEGER NOT NULL DEFAULT 0,
    active_children INTEGER NOT NULL DEFAULT 0,
    host_all        BOOLEAN NOT NULL DEFAULT false,
    gateway         BOOLEAN NOT NULL DEFAULT false,
    version         TEXT,
    payload         JSONB NOT NULL DEFAULT '{}',
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agent_runtime_supervisor_heartbeats_updated_idx
    ON agent_runtime_supervisor_heartbeats (updated_at);

-- ---------------------------------------------------------------------
-- CIPHERTEXT —— 7 张信封表，TEE 侧存明文；不带 RDS 的信封 CHECK 约束
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS chat_message_archive (
    user_id            TEXT NOT NULL,
    source_seq         BIGINT NOT NULL,
    msg_id             TEXT NOT NULL,
    ts                 DOUBLE PRECISION NOT NULL,
    doc                JSONB NOT NULL,
    storage_generation BIGINT NOT NULL DEFAULT 0,
    clear_generation   BIGINT NOT NULL,
    cleared_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (user_id, source_seq),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS model_api_credentials (
    id                 UUID NOT NULL,
    user_id            TEXT NOT NULL,
    provider           TEXT NOT NULL,
    label              TEXT NOT NULL DEFAULT '',
    base_url           TEXT NOT NULL DEFAULT '',
    api_key_envelope   JSONB NOT NULL,
    api_key_hint       TEXT NOT NULL DEFAULT '',
    supports_responses BOOLEAN NOT NULL DEFAULT false,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_conversation_summary (
    user_id                   TEXT NOT NULL,
    summary_envelope          JSONB,
    watermark_ts              DOUBLE PRECISION NOT NULL DEFAULT 0,
    version                   INTEGER NOT NULL DEFAULT 0,
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    watermark_seq             BIGINT NOT NULL DEFAULT 0,
    materialized_segment_ids  BIGINT[] NOT NULL DEFAULT '{}'::bigint[],
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_conversation_summary_segments (
    segment_id                BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id                   TEXT NOT NULL,
    format_version            SMALLINT NOT NULL DEFAULT 1,
    coverage_kind             TEXT NOT NULL DEFAULT 'exact',
    level                     SMALLINT NOT NULL,
    start_seq                 BIGINT NOT NULL,
    end_seq                   BIGINT NOT NULL,
    source_message_count      INTEGER NOT NULL,
    legacy_opaque_through_seq BIGINT NOT NULL DEFAULT 0,
    child_segment_ids         BIGINT[] NOT NULL DEFAULT '{}'::bigint[],
    summary_envelope          JSONB NOT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (segment_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_trajectory_events (
    job_id           BIGINT NOT NULL,
    user_id          TEXT NOT NULL,
    event_index      INTEGER NOT NULL,
    event_kind       TEXT NOT NULL,
    idempotency_key  TEXT NOT NULL,
    payload_envelope JSONB NOT NULL,
    payload_bytes    INTEGER NOT NULL,
    truncated        BOOLEAN NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (job_id, event_index),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_trajectory_reviews (
    source_job_id     BIGINT NOT NULL,
    user_id           TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'pending',
    attempt_count     INTEGER NOT NULL DEFAULT 0,
    claimed_by_job_id BIGINT,
    review_envelope   JSONB,
    last_error        TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    started_at        TIMESTAMPTZ,
    finished_at        TIMESTAMPTZ,
    PRIMARY KEY (source_job_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_workspace_entries (
    user_id          TEXT NOT NULL,
    path             TEXT NOT NULL,
    kind             TEXT NOT NULL,
    content_envelope JSONB NOT NULL,
    mime_type        TEXT NOT NULL DEFAULT 'text/plain',
    source_ref       TEXT NOT NULL DEFAULT '',
    revision         BIGINT NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, path),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- SNAPSHOT —— 25 张明文表，整表 TRUNCATE + COPY 原子替换
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS agent_action_queue (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id                    BIGINT NOT NULL,
    user_id                   TEXT NOT NULL,
    seq                       INTEGER NOT NULL,
    type                      TEXT NOT NULL,
    payload_json              JSONB NOT NULL DEFAULT '{}'::jsonb,
    status                    TEXT NOT NULL DEFAULT 'pending',
    visible                   BOOLEAN NOT NULL DEFAULT false,
    requires_model_authorship BOOLEAN NOT NULL DEFAULT false,
    result_json               JSONB,
    last_error                TEXT,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at                TIMESTAMPTZ,
    finished_at               TIMESTAMPTZ,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent_jobs (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                     TEXT NOT NULL,
    lane                        TEXT NOT NULL,
    status                      TEXT NOT NULL,
    reason                      TEXT,
    trace_id                    TEXT,
    priority                    INTEGER NOT NULL DEFAULT 0,
    attempt_count               INTEGER NOT NULL DEFAULT 0,
    last_error                  TEXT,
    claimed_by                  TEXT,
    invalidated_by_job_id       BIGINT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at                  TIMESTAMPTZ,
    started_at                  TIMESTAMPTZ,
    finished_at                 TIMESTAMPTZ,
    deadline_at                 TIMESTAMPTZ,
    input_generation            BIGINT NOT NULL DEFAULT 0,
    lease_expires_at            TIMESTAMPTZ,
    queue_deadline_at           TIMESTAMPTZ,
    expected_runtime_generation BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS agent_status_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id      BIGINT,
    user_id     TEXT NOT NULL,
    kind        TEXT NOT NULL,
    label       TEXT,
    detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    seq         INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_r2_cleanup (
    body_key        TEXT NOT NULL,
    user_id         TEXT NOT NULL,
    generation      BIGINT,
    reason          TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempt_count   INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_error      TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (body_key),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_r2_lifecycle (
    user_id                   TEXT NOT NULL,
    generation                BIGINT NOT NULL DEFAULT 0,
    inventory_pending          BOOLEAN NOT NULL DEFAULT false,
    inventory_next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    inventory_attempt_count   INTEGER NOT NULL DEFAULT 0,
    inventory_last_error      TEXT NOT NULL DEFAULT '',
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dau_daily_snapshot (
    day             TEXT NOT NULL,
    dau             INTEGER NOT NULL DEFAULT 0,
    chat_dau        INTEGER NOT NULL DEFAULT 0,
    tracking_dau    INTEGER NOT NULL DEFAULT 0,
    active_events   INTEGER NOT NULL DEFAULT 0,
    user_messages   INTEGER NOT NULL DEFAULT 0,
    tracking_events INTEGER NOT NULL DEFAULT 0,
    session_dau     INTEGER NOT NULL DEFAULT 0,
    avg_session_sec DOUBLE PRECISION NOT NULL DEFAULT 0,
    foreground_sec  BIGINT NOT NULL DEFAULT 0,
    session_count   INTEGER NOT NULL DEFAULT 0,
    first_ts        DOUBLE PRECISION,
    last_ts         DOUBLE PRECISION,
    frozen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    median_user_sec DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (day)
);

CREATE TABLE IF NOT EXISTS model_api_routes (
    id                       UUID NOT NULL,
    user_id                  TEXT NOT NULL,
    credential_id            UUID NOT NULL,
    model                    TEXT NOT NULL,
    reasoning_effort         TEXT,
    is_active                BOOLEAN NOT NULL DEFAULT false,
    test_status              TEXT NOT NULL DEFAULT 'untested',
    last_test_at             TIMESTAMPTZ,
    last_test_error          TEXT NOT NULL DEFAULT '',
    last_runtime_error       TEXT NOT NULL DEFAULT '',
    last_runtime_error_class TEXT NOT NULL DEFAULT '',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    context_window_tokens    BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS provider_health (
    user_id                          TEXT NOT NULL,
    provider_state                   TEXT NOT NULL DEFAULT 'ok',
    last_provider_success_at         TIMESTAMPTZ,
    last_provider_failure_at         TIMESTAMPTZ,
    last_provider_error_class        TEXT NOT NULL DEFAULT '',
    last_provider_error_blame        TEXT NOT NULL DEFAULT '',
    user_provider_failure_started_at TIMESTAMPTZ,
    last_probe_at                    TIMESTAMPTZ,
    created_at                       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS retention_cohort_snapshot (
    cohort_week  TEXT NOT NULL,
    period_index INTEGER NOT NULL,
    cohort_size  INTEGER NOT NULL DEFAULT 0,
    active_count INTEGER NOT NULL DEFAULT 0,
    frozen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (cohort_week, period_index)
);

CREATE TABLE IF NOT EXISTS runtime_state (
    user_id    TEXT NOT NULL,
    state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_growth_daily_snapshot (
    day       TEXT NOT NULL,
    new_users INTEGER NOT NULL DEFAULT 0,
    frozen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (day)
);

CREATE TABLE IF NOT EXISTS v2_capture_batches (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            TEXT NOT NULL,
    runtime_generation BIGINT NOT NULL,
    after_seq          BIGINT NOT NULL,
    through_seq        BIGINT NOT NULL,
    after_message_id   TEXT NOT NULL DEFAULT '',
    until_message_id   TEXT NOT NULL,
    until_ts           DOUBLE PRECISION NOT NULL DEFAULT 0,
    actions_json       JSONB NOT NULL,
    action_count       INTEGER NOT NULL,
    status             TEXT NOT NULL DEFAULT 'prepared',
    prepared_by_job_id BIGINT,
    applied_by_job_id  BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    applied_at         TIMESTAMPTZ,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_effect_outbox (
    effect_id           TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    job_id              BIGINT,
    effect_type         TEXT NOT NULL,
    expected_generation BIGINT NOT NULL,
    payload             JSONB NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_at          TIMESTAMPTZ,
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    last_error          TEXT NOT NULL DEFAULT '',
    enqueue_seq         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    last_attempt_at     TIMESTAMPTZ,
    next_attempt_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    input_frontier_seq  BIGINT,
    PRIMARY KEY (effect_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_effect_sink_applied (
    effect_id    TEXT NOT NULL,
    applied_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    claim_state  TEXT NOT NULL DEFAULT 'claimed',
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (effect_id)
);

CREATE TABLE IF NOT EXISTS v2_mcp_mutation_attempts (
    job_id             BIGINT NOT NULL,
    user_id            TEXT NOT NULL,
    input_frontier_seq BIGINT NOT NULL,
    call_key           CHARACTER(64) NOT NULL,
    tool_fingerprint   CHARACTER(64) NOT NULL,
    started_at         TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    resolved_at        TIMESTAMPTZ,
    outcome            TEXT,
    PRIMARY KEY (job_id, call_key),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_runtime_control (
    id                    INTEGER NOT NULL DEFAULT 1,
    turns_halted          BOOLEAN NOT NULL DEFAULT false,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    web_search_halted     BOOLEAN NOT NULL DEFAULT false,
    web_fetch_halted      BOOLEAN NOT NULL DEFAULT false,
    provider_usage_halted BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v2_runtime_state (
    user_id              TEXT NOT NULL,
    hosted_runtime_state TEXT NOT NULL DEFAULT 'resident',
    runtime_generation   BIGINT NOT NULL DEFAULT 1,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_sandbox_usage_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     TEXT NOT NULL,
    provider    TEXT NOT NULL,
    purpose     TEXT NOT NULL,
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_at TIMESTAMPTZ,
    duration_ms BIGINT,
    outcome     TEXT NOT NULL DEFAULT 'acquired',
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_terminal_failure_outbox (
    job_id                        BIGINT NOT NULL,
    user_id                       TEXT NOT NULL,
    error_code                    TEXT NOT NULL,
    target_route_id               UUID,
    target_route_updated_at       TIMESTAMPTZ,
    status_delivered_at           TIMESTAMPTZ,
    runtime_error_delivered_at    TIMESTAMPTZ,
    status_attempt_count          INTEGER NOT NULL DEFAULT 0,
    status_last_attempt_at        TIMESTAMPTZ,
    status_next_attempt_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    runtime_error_attempt_count   INTEGER NOT NULL DEFAULT 0,
    runtime_error_last_attempt_at TIMESTAMPTZ,
    runtime_error_next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (job_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_trajectory_access_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    access_id   UUID NOT NULL,
    phase       TEXT NOT NULL,
    user_id     TEXT NOT NULL,
    job_id      BIGINT NOT NULL,
    operator_id TEXT NOT NULL,
    reason_code TEXT NOT NULL,
    case_ref    TEXT NOT NULL,
    event_count INTEGER,
    result_code TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_trajectory_streams (
    job_id           BIGINT NOT NULL,
    user_id          TEXT NOT NULL,
    next_event_index INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (job_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_turn_metrics (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id                  BIGINT,
    user_id                 TEXT,
    lane                    TEXT,
    prompt_tokens           BIGINT,
    completion_tokens       BIGINT,
    latency_ms              INTEGER,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    model_calls             INTEGER NOT NULL DEFAULT 0,
    retries                 INTEGER NOT NULL DEFAULT 0,
    failed                  BOOLEAN NOT NULL DEFAULT false,
    status                  TEXT,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    provider                TEXT,
    model                   TEXT,
    cache_route_fingerprint TEXT,
    cache_read_tokens       BIGINT,
    cache_write_tokens      BIGINT,
    cache_miss_tokens       BIGINT,
    usage_reported_calls    INTEGER NOT NULL DEFAULT 0,
    cache_reported_calls    INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_user_allowlist (
    user_id    TEXT NOT NULL,
    desired    TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by TEXT NOT NULL DEFAULT '',
    note       TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_wake_schedule (
    user_id                    TEXT NOT NULL,
    next_heartbeat_at          TIMESTAMPTZ,
    next_capture_at            TIMESTAMPTZ,
    payment_cooldown_until     TIMESTAMPTZ,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    next_screen_watch_at       TIMESTAMPTZ,
    last_screen_watch_frame_id TEXT,
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS v2_worker_heartbeats (
    worker_id TEXT NOT NULL,
    beat_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    kind      TEXT NOT NULL DEFAULT 'turn',
    capacity  INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (worker_id)
);
"""


def upgrade() -> None:
    op.execute(_DDL)


def downgrade() -> None:
    # 与 0001 baseline 同策略：影子库的 downgrade 不实现——回滚手段是重建库 +
    # 从 WAL-G 恢复，不是逐表 DROP（DROP 会连带毁掉已复制的数据）。
    raise NotImplementedError("alembic_tee 不支持 downgrade；回滚走 WAL-G 恢复")
