"""Add V1 chat activity metadata to the TEE SNAPSHOT lane.

Revision ID: 0007_chat_activity_snapshot
Revises: 0006_terminal_failure_reply
Create Date: 2026-07-29

``chat_turn_activity_events`` contains only fixed identifiers, state, timing,
and pre-projected display metadata. Tool arguments, result bodies, and model
prose are rejected before they reach the RDS table, so the table is safe to
copy as plaintext.

The RDS table has a composite foreign key to ``chat_messages``. The TEE copy
intentionally omits that cross-lane foreign key: chat messages arrive through
the independent CIPHERTEXT lane, while this table is atomically replaced by
SNAPSHOT. Keeping the FK would make a valid activity snapshot fail whenever
the parent message has not reached the TEE yet. This matches the cross-lane FK
policy used by 0004_full_table_alignment.
"""

from alembic import op


revision = "0007_chat_activity_snapshot"
down_revision = "0006_terminal_failure_reply"
branch_labels = None
depends_on = None


_UP = """
CREATE TABLE IF NOT EXISTS chat_turn_activity_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     TEXT NOT NULL,
    turn_id     TEXT NOT NULL,
    activity_id TEXT NOT NULL,
    tool_name   TEXT NOT NULL,
    state       TEXT NOT NULL
                CHECK (state IN ('running', 'success', 'failure')),
    call_id     TEXT,
    detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    UNIQUE (user_id, turn_id, activity_id, state)
);
"""

_DOWN = """
DROP TABLE IF EXISTS chat_turn_activity_events;
"""


def upgrade() -> None:
    op.execute(_UP)


def downgrade() -> None:
    op.execute(_DOWN)
