"""Backfill the V2 seq cursor and give outbox effects a total enqueue order.

Revision ID: 0033_v2_seq_cursor_effect_order
"""
from alembic import op


revision = "0033_v2_seq_cursor_effect_order"
down_revision = "0032_merge_tee_v2"
branch_labels = None
depends_on = None


_UP = r"""
ALTER TABLE v2_effect_outbox
  ADD COLUMN IF NOT EXISTS enqueue_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Adding an identity column assigns values to pre-existing rows in physical
-- scan order, which is not a durable semantic order. Preserve the old queue's
-- created_at ordering explicitly (effect_id is the deterministic tie-breaker),
-- then move the identity sequence beyond the backfill. The table ALTER lock is
-- held until this migration commits, so no producer can interleave an insert.
-- Drop first for idempotent/manual re-execution: an existing non-deferrable
-- unique index could otherwise reject a transient 2->1 / 3->2 renumber even
-- though the final sequence is unique.
DROP INDEX IF EXISTS v2_effect_outbox_enqueue_seq_unique;

WITH ordered AS (
  SELECT effect_id,
         ROW_NUMBER() OVER (ORDER BY created_at ASC, effect_id ASC) AS new_seq
  FROM v2_effect_outbox
)
UPDATE v2_effect_outbox AS effects
SET enqueue_seq = ordered.new_seq
FROM ordered
WHERE effects.effect_id = ordered.effect_id;

SELECT setval(
  pg_get_serial_sequence('v2_effect_outbox', 'enqueue_seq'),
  COALESCE((SELECT MAX(enqueue_seq) FROM v2_effect_outbox), 1),
  EXISTS (SELECT 1 FROM v2_effect_outbox)
);

CREATE UNIQUE INDEX IF NOT EXISTS v2_effect_outbox_enqueue_seq_unique
  ON v2_effect_outbox (enqueue_seq);

-- The original sink ledger inserted its only marker before performing the
-- durable write.  A hard process death in that interval is ambiguous whenever
-- the matching outbox row is still pending: the write may or may not have
-- landed.  Never reinterpret that marker as success.  Leave it claimed and
-- move the outbox row to explicit manual reconciliation.  This UPDATE also
-- repairs databases on which an earlier build of this migration already
-- backfilled every legacy row to completed: that build set completed_at equal
-- to applied_at, whereas the new two-phase protocol completes in a later
-- transaction and therefore records a distinct timestamp.
ALTER TABLE v2_effect_sink_applied
  ADD COLUMN IF NOT EXISTS claim_state TEXT,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

UPDATE v2_effect_outbox AS effect
SET status = 'needs_reconciliation',
    last_error = 'legacy sink delivery uncertain: manual reconciliation required',
    attempt_count = GREATEST(attempt_count, 1),
    last_attempt_at = COALESCE(last_attempt_at, now())
FROM v2_effect_sink_applied AS sink
WHERE sink.effect_id = effect.effect_id
  AND effect.status = 'pending'
  AND (
    sink.claim_state IS NULL
    OR (
      sink.claim_state = 'completed'
      AND sink.completed_at = sink.applied_at
    )
  );

-- Legacy model-authored write args were plaintext.  An ambiguous delivery can
-- no longer be replayed automatically, so retaining those args only extends a
-- confidentiality bug without making reconciliation safe.  Operators inspect
-- the target state and ask the user to repeat the write if necessary.
UPDATE v2_effect_outbox AS effect
SET payload = '{"legacy_payload_scrubbed": true}'::jsonb
FROM v2_effect_sink_applied AS sink
WHERE sink.effect_id = effect.effect_id
  AND effect.status = 'needs_reconciliation'
  AND effect.last_error = 'legacy sink delivery uncertain: manual reconciliation required'
  AND effect.effect_type IN ('memory', 'identity', 'schedule');

UPDATE v2_effect_sink_applied AS sink
SET claim_state = 'claimed',
    completed_at = NULL
FROM v2_effect_outbox AS effect
WHERE effect.effect_id = sink.effect_id
  AND effect.status = 'needs_reconciliation'
  AND effect.last_error = 'legacy sink delivery uncertain: manual reconciliation required'
  AND (
    sink.claim_state IS NULL
    OR (
      sink.claim_state = 'completed'
      AND sink.completed_at = sink.applied_at
    )
  );

-- A legacy marker is safe to treat as completed only when its outbox row was
-- already terminal (or no longer exists).  New rows always set claim_state at
-- INSERT and are untouched by this backfill.
UPDATE v2_effect_sink_applied
SET claim_state = 'completed',
    completed_at = COALESCE(completed_at, applied_at)
WHERE claim_state IS NULL;

ALTER TABLE v2_effect_sink_applied
  ALTER COLUMN claim_state SET DEFAULT 'claimed',
  ALTER COLUMN claim_state SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'v2_effect_sink_applied_claim_state_check'
      AND conrelid = 'v2_effect_sink_applied'::regclass
  ) THEN
    ALTER TABLE v2_effect_sink_applied
      ADD CONSTRAINT v2_effect_sink_applied_claim_state_check
      CHECK (claim_state IN ('claimed', 'completed'));
  END IF;
END $$;

DROP INDEX IF EXISTS v2_effect_outbox_pending;
CREATE INDEX IF NOT EXISTS v2_effect_outbox_pending
  ON v2_effect_outbox (user_id, enqueue_seq)
  WHERE status = 'pending';

-- Terminal legacy tool rows no longer need their plaintext arguments. Pending
-- rows are left intact for the compatibility consumer, which scrubs them in
-- the same transaction that applies/discards them.
UPDATE v2_effect_outbox
SET payload = '{"legacy_payload_scrubbed": true}'::jsonb
WHERE status IN ('applied', 'discarded')
  AND effect_type IN ('memory', 'identity', 'schedule');

UPDATE v2_conversation_summary AS summary
SET watermark_seq = COALESCE((
  SELECT MAX(messages.seq)
  FROM chat_messages AS messages
  WHERE messages.user_id = summary.user_id
    AND messages.ts < summary.watermark_ts
), 0)
WHERE summary.watermark_seq = 0
  AND summary.watermark_ts > 0;

WITH legacy AS (
  SELECT state.user_id, COALESCE(MAX(messages.seq), 0)::bigint AS cursor_seq
  FROM runtime_state AS state
  LEFT JOIN chat_messages AS messages
    ON messages.user_id = state.user_id
   AND messages.ts < (state.state_json ->> 'last_replied_ts')::double precision
  WHERE (state.state_json ->> 'last_replied_ts')
        ~ '^[0-9]+([.][0-9]+)?$'
  GROUP BY state.user_id
)
INSERT INTO user_blobs (user_id, kind, doc)
SELECT user_id, 'model_api_runtime',
       jsonb_build_object('v2_reply_cursor_seq', cursor_seq)
FROM legacy
ON CONFLICT (user_id, kind) DO UPDATE
SET doc = user_blobs.doc || jsonb_build_object(
  'v2_reply_cursor_seq',
  GREATEST(
    CASE
      WHEN COALESCE(user_blobs.doc ->> 'v2_reply_cursor_seq', '') ~ '^[0-9]+$'
      THEN (user_blobs.doc ->> 'v2_reply_cursor_seq')::bigint
      ELSE 0
    END,
    (EXCLUDED.doc ->> 'v2_reply_cursor_seq')::bigint
  )
);
"""


_DOWN = """
-- A two-phase claim without completion is ambiguous.  Old code only knows
-- marker-present == completed, so terminalize it for manual reconciliation
-- before removing the state columns; otherwise an image/schema rollback could
-- silently convert an uncertain delivery into success.
UPDATE v2_effect_outbox AS effect
SET status = 'needs_reconciliation',
    last_error = 'sink delivery uncertain during schema rollback: manual reconciliation required',
    attempt_count = GREATEST(attempt_count, 1)
FROM v2_effect_sink_applied AS sink
WHERE sink.effect_id = effect.effect_id
  AND sink.claim_state = 'claimed'
  AND effect.status = 'pending';

UPDATE v2_effect_outbox AS effect
SET payload = '{"legacy_payload_scrubbed": true}'::jsonb
FROM v2_effect_sink_applied AS sink
WHERE sink.effect_id = effect.effect_id
  AND sink.claim_state = 'claimed'
  AND effect.status = 'needs_reconciliation'
  AND effect.last_error = 'sink delivery uncertain during schema rollback: manual reconciliation required'
  AND effect.effect_type IN ('memory', 'identity', 'schedule');

DROP INDEX IF EXISTS v2_effect_outbox_pending;
DROP INDEX IF EXISTS v2_effect_outbox_enqueue_seq_unique;
CREATE INDEX IF NOT EXISTS v2_effect_outbox_pending
  ON v2_effect_outbox (user_id, created_at)
  WHERE status = 'pending';
ALTER TABLE v2_effect_outbox DROP COLUMN IF EXISTS enqueue_seq;
ALTER TABLE v2_effect_outbox
  DROP COLUMN IF EXISTS last_attempt_at,
  DROP COLUMN IF EXISTS next_attempt_at;
ALTER TABLE v2_effect_sink_applied
  DROP CONSTRAINT IF EXISTS v2_effect_sink_applied_claim_state_check,
  DROP COLUMN IF EXISTS completed_at,
  DROP COLUMN IF EXISTS claim_state;
"""


def upgrade() -> None:
    op.execute(_UP)


def downgrade() -> None:
    # Cursor/summary backfills are intentionally monotonic and are not erased.
    op.execute(_DOWN)
